services:
  - type: web
    name: survey-app
    env: java
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/survey-app.jar
    healthCheckPath: /
    envVars:
      - key: PORT
        generateValue: true