services:
  - type: web
    name: survey-app
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/survey-app.jar
    healthCheckPath: /
    envVars:
      - key: PORT
        generateValue: true